#scp -pr /Users/hoangnd/Documents/code/udemy/ShopApp/sql root@45.117.179.175:/root/

#scp -pr /Users/hoangnd/Documents/code/udemy/ShopApp/backend root@45.117.179.175:/root/
#scp -pr /Users/hoangnd/Documents/code/udemy/ShopApp/backend/src/main/resources/application.yaml root@45.117.179.175:/root/backend/src/main/resources/
#scp -pr /Users/hoangnd/Documents/code/udemy/ShopApp/backend/pom.xml root@45.117.179.175:/root/backend/pom.xml
#scp -pr /Users/hoangnd/Documents/code/udemy/ShopApp/deployment.yaml root@45.117.179.175:/root/
#scp -pr /Users/hoangnd/Documents/code/udemy/ShopApp/DockerfileJavaSpring root@45.117.179.175:/root/

#Deploy angular app
#copy angular code to server
#rm -rf /Users/hoangnd/Documents/code/udemy/ShopApp/fontend/node_modules
#scp -r /Users/hoangnd/Documents/code/udemy/ShopApp/fontend root@45.117.179.175:/root/
#scp -r /Users/hoangnd/Documents/code/udemy/ShopApp/fontend/src/app/environments/environment.ts root@45.117.179.175:/root/fontend/src/app/environments/
#scp -pr /Users/hoangnd/Documents/code/udemy/ShopApp/DockerfileAngular root@45.117.179.175:/root/
#scp -pr /Users/hoangnd/Documents/code/udemy/ShopApp/deployment.yaml root@45.117.179.175:/root/

version: '3.7'
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 184466874
      MYSQL_DATABASE: ShopApp
    ports:
      - 3307:3306
    volumes: 
      - ./sql/shopapp.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - shopapp-network

  phpmyadmin8-container:
    #intel host
    image: phpmyadmin/phpmyadmin
    #mac m1 host
    #image: arm64v8/phpmyadmin     
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container      
    ports:
      - "8100:80" #port mapping
    environment:
      PMA_HOST: mysql8-container #phpMyAdmin Host
    networks:
      - shopapp-network
  
  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379" # Port mapping for Redis, you can change the host port as needed
    volumes:
      - ./redis-data:/data # Mount a volume for Redis data persistence
    networks:
      - shopapp-network

  shopapp-spring-container:    
    container_name: shopapp-spring-container    
    build:
      context: .
      dockerfile: DockerfileJavaSpring      
      #docker tag <image_id> shopapp-spring:1.0.0    
    ports:
      - 8099:8088
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-container:3306/ShopApp?serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-container:3306/ShopApp?serverTimezone=UTC&allowPublicKeyRetrieval=true
      MYSQL_ROOT_PASSWORD: 184466874
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
    #depends_on only waits for the container to start, not for the service inside the container to be fully operational
    depends_on:      
      - mysql8-container
    networks:
      - shopapp-network    
    healthcheck:
      #test: ["CMD-SHELL", "curl --fail http://localhost:8088/healthcheck/health || exit 1"]
      test: ["CMD-SHELL", "curl --fail http://localhost:8088/api/v1/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s #20s after container created, health check     

  fontend-container:    
    container_name: fontend-container    
    build:
      context: .
      dockerfile: DockerfileAngular            
      #docker tag <image_id> fontend:1.0.0
    ports:
      - "4301:80"
    restart: always    
    networks:
      - shopapp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3            
          
networks:
  shopapp-network:
    name: shopapp-network
    driver: bridge

#docker-compose -f ./deployment.yaml down 

#docker-compose -f ./deployment.yaml rm -s -f mysql8-container
#docker-compose -f ./deployment.yaml up -d mysql8-container

#docker-compose -f ./deployment.yaml rm -s -f phpmyadmin8-container
#docker-compose -f ./deployment.yaml up -d phpmyadmin8-container


#docker-compose -f ./deployment.yaml rm -s -f shopapp-spring-container 
#docker-compose -f ./deployment.yaml up -d shopapp-spring-container --build
#docker logs shopapp-spring-container

#docker-compose -f ./deployment.yaml rm -s -f fontend-container
#docker-compose -f ./deployment.yaml up -d fontend-container
#docker logs fontend-container 

#docker-compose -f ./deployment.yaml rm -s -f redis-container
#docker-compose -f ./deployment.yaml up -d redis-container

#docker-compose -f ./deployment.yaml rm -s -f debezium-kafka-container
#docker-compose -f ./deployment.yaml up -d debezium-kafka-container
#docker-compose -f ./deployment.yaml up -d debezium-connect-container




